import { TrendTopic } from './types';

export const CLIENT_FALLBACK_TRENDS: TrendTopic[] = [
  {
    id: "trend-metgala",
    keyword: "Met Gala Red Carpet",
    platform: "instagram",
    category: "Pop Culture",
    engagementScore: 99,
    relativeTime: "5 mins ago",
    description: "Internet creators are reacting to breathtaking avant-garde fashion statements, dramatic floral installations, and hand-crafted silhouettes on the Met Gala steps.",
    whyTrending: "Custom botanical-themed gowns and high-fashion arrivals triggered viral outfit comparisons and aesthetic design edits worldwide.",
    viralPostExample: "Me criticizing multi-million dollar Met Gala ensembles while wearing a 5-year-old stained pajama set. 👁️👄👁️💅",
    hashtags: ["MetGala", "GalaFashion", "RedCarpetLooks", "AvantGardeAesthetic"],
    region: "Global",
    city: "Global",
    volume: "3.1M Reels"
  },
  {
    id: "trend-ghibli",
    keyword: "Studio Ghibli Nostalgia",
    platform: "instagram",
    category: "Entertainment",
    engagementScore: 98,
    relativeTime: "15 mins ago",
    description: "Nostalgic animation fans are sharing heartwarming morning routine and desk aesthetic loops layered with watercolor filters and soft piano adaptations of Studio Ghibli soundtracks.",
    whyTrending: "The sudden popularity of customized hand-drawn anime shader filters prompted thousands of relaxing room decor and slow-living clips.",
    viralPostExample: "Romanticizing my normal workday by pretending I am a character in a Ghibli movie washing dishes. 🧼✨",
    hashtags: ["GhibliAesthetic", "AnimeLofi", "StudioGhibli", "AmbientNostalgia"],
    region: "Global",
    city: "Global",
    volume: "1.2M Reels"
  },
  {
    id: "trend-holi",
    keyword: "Holi Joy Splashes",
    platform: "instagram",
    category: "Pop Culture",
    engagementScore: 99,
    relativeTime: "30 mins ago",
    description: "Dynamic high-speed camera throws of organic color pigments, white linen transformation transitions, and joyous street dancing celebrating the festival of Holi.",
    whyTrending: "Celebrity celebrations and vibrant slow-motion powder cloud captures dominated mainstream video feeds this spring.",
    viralPostExample: "The pristine white outfit didn't stand a chance. Happy Holi, active world! 🎨❤️",
    hashtags: ["HoliFestival", "ColorSplashes", "OrganicGulal", "HoliVibes"],
    region: "Indian",
    city: "Delhi",
    volume: "4.5M Reels"
  },
  {
    id: "trend-mothersday",
    keyword: "Mother's Day Nostalgia",
    platform: "instagram",
    category: "Pop Culture",
    engagementScore: 95,
    relativeTime: "1 hour ago",
    description: "Users are assembling heartwarming childhood-and-parent comparative overlays, sharing funny maternal text screen grabs, and paying tribute to their mother's unconditional support.",
    whyTrending: "A viral template prompting creators to overlay their own kids with baby photos of their mothers triggered a global wave of sentimental posts.",
    viralPostExample: "Recreating my 1998 baby photo and realizing my mother has been doing all the heavy lifting since day one. 🥺❤️",
    hashtags: ["MothersDay", "ThanksMom", "VintageChildhood", "WarmFamilyAesthetic"],
    region: "Global",
    city: "Global",
    volume: "2.3M posts"
  },
  {
    id: "trend-aireplace",
    keyword: "AI Will Replace You Meme",
    platform: "twitter",
    category: "Meme",
    engagementScore: 93,
    relativeTime: "45 mins ago",
    description: "Lively satire showcasing major funny fails, silly outputs of generative models, or robots getting physically stuck on simple items, sarcastically assuring creators that jobs are perfectly safe.",
    whyTrending: "A viral series of images capturing generative engines failing to render a human successfully holding chopsticks sparked worldwide tech parody threads.",
    viralPostExample: "AI is ready to take over our entire digital society! Meanwhile, AI trying to distinguish a chocolate muffin from a chihuahua: 🐕🧁",
    hashtags: ["AIWillReplaceYou", "TechHumor", "AIRuntimeFail", "SoftwareJokes"],
    region: "Global",
    city: "Global",
    volume: "920K posts"
  },
  {
    id: "trend-fifa",
    keyword: "FIFA Soundtrack Nostalgia",
    platform: "instagram",
    category: "Sports",
    engagementScore: 92,
    relativeTime: "3 hours ago",
    description: "Football fans edit nostalgic sports compilations and historical game highlights set to classic, high-octane FIFA game soundtrack anthems from the late 2000s.",
    whyTrending: "A trending sports handle's video linking iconic tournament history with vintage indie rock songs re-triggered collective memories.",
    viralPostExample: "Hearing this specific song instantly increases my morning productivity level by 300%. ⚽️🎮",
    hashtags: ["FIFASoundtracks", "FootballHighlight", "EAClassicVibes", "NostalgiaUncapped"],
    region: "Global",
    city: "Global",
    volume: "1.7M Reels"
  },
  {
    id: "trend-biryani",
    keyword: "The Biryani 'Consent' Row",
    platform: "linkedin",
    category: "Business",
    engagementScore: 94,
    relativeTime: "2 hours ago",
    description: "A passionate food dispute examining whether cooking cardamoms (elaichi) or potatoes in traditional Biryani layouts without explicitly warning guests constitutes a breach of dining 'consent.'",
    whyTrending: "A funny, long-form satirical post by a tech director equating biting into a hidden cardamom with critical product design bugs went viral.",
    viralPostExample: "Can we all agree that biting into a hidden elaichi is an absolute violation of culinary user experience? ❌🍛",
    hashtags: ["BiryaniConsent", "ProductDesignLessons", "CulinaryUX", "LinkedInPulseDesi"],
    region: "Indian",
    city: "Delhi",
    volume: "340K interactions",
    linkedinContext: "B2B Creator Debate Level: Extreme (+95% Engagement)"
  },
  {
    id: "trend-viratlook",
    keyword: "Virat Kohli's New Look",
    platform: "twitter",
    category: "Sports",
    engagementScore: 97,
    relativeTime: "10 mins ago",
    description: "Cricket icon debuted a razor-sharp fade haircut, styled beard trim, and sleek custom designer eyewear prior to matches.",
    whyTrending: "Celebrity stylists uploaded spectacular behind-the-scenes grooming clips, triggering instant nation-wide barbershop look copying.",
    viralPostExample: "Walking into work tomorrow hoping my peers recognize the absolute aura shift after getting the Kohli fade. 💇‍♂️🏏",
    hashtags: ["ViratKohliLook", "CricketFashion", "KingKohliNewHair", "DesiBarberScreener"],
    region: "Indian",
    city: "Mumbai",
    volume: "3.2M interactions"
  },
  {
    id: "trend-delhimetro",
    keyword: "Delhi Metro Fashion Walk",
    platform: "instagram",
    category: "Meme",
    engagementScore: 94,
    relativeTime: "1 hour ago",
    description: "Creators are staging impromptu runway walks and aesthetic slow-motion videos inside Delhi Metro stations, sparking debates on public commuting etiquette.",
    whyTrending: "A humorous video contrasting highly-glamorous designer outfits with packed morning transit crowds gained 8M views.",
    viralPostExample: "Who needs Paris Fashion Week when you have the Yellow Line interchange? 🚇💅",
    hashtags: ["DelhiMetro", "MetroFashion", "YellowLineChronicles", "DelhiDiaries"],
    region: "Indian",
    city: "Delhi",
    volume: "450K posts"
  },
  {
    id: "trend-mumbailocal",
    keyword: "Mumbai Local Survival Hacks",
    platform: "instagram",
    category: "Meme",
    engagementScore: 96,
    relativeTime: "2 hours ago",
    description: "Commuters are sharing dramatic 'survival guides' and cinematic slow-motion videos boarding the peak-hour Mumbai local train with dramatic action movie music.",
    whyTrending: "A hilarious reel showing a corporate employee executing a perfect acrobatic leap into a moving train labeled 'The Agile Scrum Master' went viral.",
    viralPostExample: "Doing a complete physical workout just to reach my 9 AM standup in Lower Parel. 🏃‍♂️🚆",
    hashtags: ["MumbaiLocal", "TrainHacks", "LowerParelLife", "MumbaiMonsoon"],
    region: "Indian",
    city: "Mumbai",
    volume: "580K Reels"
  },
  {
    id: "trend-bangaloreauto",
    keyword: "Bangalore Auto Tech Meters",
    platform: "twitter",
    category: "Tech",
    engagementScore: 93,
    relativeTime: "4 hours ago",
    description: "A viral campaign capturing Bangalore auto-rickshaws displaying custom QR code tablets that share startup elevator pitches and peak-hour rate negotiations.",
    whyTrending: "A tech founder posted an auto driver who offered feedback on their seed pitch deck in exchange for riding 'meter-plus-thirty', triggering huge tech startup humor threads.",
    viralPostExample: "My Bangalore auto driver just asked for my startup's CAC and LTV before agreeing to go to Indiranagar. 🛺📈",
    hashtags: ["BangaloreStartups", "OnlyInBangalore", "PeakBangalore", "AutoRickshawTech"],
    region: "Indian",
    city: "Bangalore",
    volume: "290K tweets"
  }
];
